name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
    - name: Rename directories
      run: |
        mkdir 4.40
        mv Binary_4.40 4.40/Widgets.Flixmedia
        mv Source_4.40 4.40/DFar.Plugin.Widgets.Flixmedia
    - uses: dfar-io/nopcommerce-uploadeditems-action@main
      with:
        plugin-name: 'DFar.Plugin.Widgets.Flixmedia'
    - name: Zip artifact files
      run: 7z a Flixmedia.zip .
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: Flixmedia.zip